### ISSUE TITLE
Battery problem

### ISSUE THREAD

**Issue by sicay1** [G4lile0/Bobwi#5]
Hi All,
Anyone got battery problem like me. With cheap 4x AA battery, bluetooth HC-06 not running (no power). With 4x AA Energizer Bobwi can only run about 1 hour and then HC-06 not running (like cheap battery)

My Bobwi part:
1. Arduino nano
2. nano shield
3. bluetooth HC06
4. servo 9g x4
5. Battery AA x4 (picture http://media.vatgia.vn/ir_type6/zjf1295920515.jpg)

I was using this code:
Control the robot from your Android phone:
Download the official "Zowi App" from bq
Configure the bluetooth module using this code: https://github.com/G4lile0/Bobwi/tree/master/code/v2/arduino/code/hc06_bt_config
Then load the Zowi base v2 software: https://github.com/G4lile0/Bobwi/tree/master/code/v2/arduino/code/ZOWI_BASE_v2

Tony .

**Comment by poyaque-estamos** [comment]
Cant' really answer about batteries since I haven't even connected mine yet. But what goes for usb connection I can tell you it is also very sensitive to it. I can only make it work with the cable that came with the arduino and connected to the computer. Any other combinations of cable/source don't work.

More in detail, when i mean work, i mean being able to control it from the zowi app. For example, I can connect it via usb to a usb charger and the robot might seem to normally start, but it doesn't answer to the app correctly (the app says it is connected though). In other cases it doesn't even start correctly at all and the app doesn't show it as connected either.

**Comment by G4lile0** [comment]
Servos consume a lot, and drop the battery voltage under 5V or 3,3V and reset the arduino, to solve this add this circuit: (consider 6V instead of the 5V of the image) 

![image](https://cloud.githubusercontent.com/assets/16692715/20652908/707f95e8-b503-11e6-97d9-3afb27984491.png)
For the capacitor use > 1000uF and > 6V

In order to make Bobwi work to the app, you have add a button for A0, or just a single wire, and touch it, to make Bobwi change to app mode.

**Comment by edmondhuang** [comment]
Hi All,

There should be problem with Nano Sheild, it can't go through big currents, I think. What my solution is as below.

* 5V power supply directly, using LiPo battery with 5V/4A rise circuit.

**Comment by sicay1** [comment]
many thanks, G4lile0. 
Haven't try you diagram yet, need to learn more basic electronics, circuits.

@poyaque-estamos i got no problem when using USB cable control Bobwi over bluetooth
